development:
  adapter: postgresql
  encoding: unicode
  database: t_portal_development
  host: localhost
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: t_portal_test
  host: localhost
  pool: 5
  username: postgres
  password: postgres
  